name: Docker_build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.IAP_TOKEN }}
          
    - name: docker image build
      run: |
        docker build -t docker.pkg.github.com/hmharsh/degital_ocean_node/node_server:1.0.0 .
    - name: docker image push
      run: |
        docker push docker.pkg.github.com/hmharsh/degital_ocean_node/node_server:1.0.0
